{% set name = "ngsderive" %}
{% set version = "2.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0c4edcdc32bcf6cbd2aea46fe72f156ef24f30a9c9213f38f48dff7b36951d6f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - poetry
  run:
    - colorlog
    - pysam 0.15.3
    - pytabix >=0.1
    - python >=3.7
    - rstr >=2.2.6
    - poetry
    - gtfparse >=1.2.1
    - sortedcontainers >=2.3.0
    - colorlog >=4.0.2
    - tabix >=1.11

test:
  imports:
    - ngsderive
    - ngsderive.commands
    - ngsderive.readers
  commands:
    - ngsderive --help

about:
  home: https://github.com/claymcleod/ngsderive
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "Backwards derive attributes from NGS data"
  doc_url: https://github.com/claymcleod/ngsderive
  dev_url: https://github.com/claymcleod/ngsderive

extra:
  recipe-maintainers:
    - claymcleod
    - a-frantz
