# .circleci/config.yml
version: 2.1

executors:
  osx-arm64:
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    resource_class: macos.m1.large.gen1
  linux-aarch64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

jobs: # a basic unit of work in a run
  build_and_test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout

      - run:
          name: Fetch bioconda install script
          command: wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/install-and-set-up-conda.sh

      - restore_cache:
          keys:
            - bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}

      - run:
          name: Install bioconda-utils
          command: |
            sudo mkdir -p /opt/miniconda
            sudo chown -R $USER /opt/miniconda
            bash install-and-set-up-conda.sh

      - save_cache:
          key: bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}
          paths:
            - /opt/miniconda

      - run:
          name: Build and test
          command: |
            conda activate bioconda-utils
            bioconda-utils build recipes config.yml --git-range origin/master HEAD

      - run:
          name: Prepare artifacts
          command: |
            (
            mkdir -p /tmp/artifacts/packages
            cd /opt/miniconda/envs/bioconda/conda-bld || exit 0
            find -name .cache | xargs rm -rf || true
            for n in index.html channeldata.json linux-64 osx-64 noarch; do
              cp -rv $n /tmp/artifacts/packages || true
            done
            ) || true

      - store_artifacts:
          path: /tmp/artifacts

  build_and_push:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout

      - run:
          name: Fetch bioconda install script
          command: wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/install-and-set-up-conda.sh

      - restore_cache:
          keys:
            - bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}

      - run:
          name: Install bioconda-utils
          command: |
            sudo mkdir -p /opt/miniconda
            chown -R $USER:$USER /opt/miniconda
            bash install-and-set-up-conda.sh

      - save_cache:
          key: bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}
          paths:
            - /opt/miniconda

      - run:
          name: Build and push
          command: |
            conda activate bioconda-utils
            # TODO we need to update bioconda-utils with support for retrieving circleci artifacts from above
            bioconda-utils handle-merged-pr recipes config.yml \
              --repo bioconda/bioconda-recipes \
              --git-range ${CIRCLE_SHA1}~1 ${CIRCLE_SHA1} \
              --fallback build

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master
          matrix:
            parameters:
              os: [osx-arm64, linux-aarch64]
  build_and_push:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: master
          matrix:
            parameters:
              os: [osx-arm64, linux-aarch64]
