{% set name = "diapysef" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: af5df4ceb74587a6bef4d323b01bcc6d31d595fe415fcda83e3184a21de416db

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas
    - patsy
    - pyopenms
    - python
    - statsmodels

test:
  imports:
    - diapysef

about:
  home: "https://github.com/Roestlab/dia-pasef"
  license: MIT
  license_family: MIT
  summary: "Analysis, conversion and visualization of diaPASEF data."

extra:
  recipe-maintainers:
    - bgruening
