{% set name = "diapysef" %}
{% set version = "1.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 373ddef4cfd83b30c9c9e345d0fff3b35362a63b0d8e83212dbf0828d708137d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas
    - patsy
    - pyopenms
    - python
    - statsmodels
    - seaborn
    - tqdm
    - joblib
    - click
    - opencv

test:
  imports:
    - diapysef

about:
  home: "https://github.com/Roestlab/dia-pasef"
  license: MIT
  license_family: MIT
  summary: "Analysis, conversion and visualization of diaPASEF data."

extra:
  recipe-maintainers:
    - bgruening
