{% set version = "1.0.0" %}

package:
  name: nthits
  version: {{ version }}

source:
  url: https://github.com/bcgsc/ntHits/archive/v{{ version }}.tar.gz
  sha256: 37ff2afb3f6561a0c4e0a7f8e5b2986733a813658b66c83918ecf8365e4da6ed

build:
  number: 0

requirements:
  build:
    - make
    - automake
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  run:
    - llvm-openmp  # [osx]

test:
  commands:
    - nthits --help

about:
  home: https://github.com/bcgsc/ntHits
  license: MIT
  license_file: LICENSE
  summary: a method for identifying repeats in high-throughput DNA sequencing data.
