{% set version="1.0.0" %}

package:
  name: quatradis
  version: {{ version }}

source:
  url: https://github.com/quadram-institute-bioscience/QuaTradis/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9f14e710f2a20013ce1eb1fdb9931bf478222e27eaa0312f533c399420c4ec89

build:
  number: 0
  noarch: python
  script: python -m pip install -v --no-deps --ignore-installed .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools  # for pkg_resources
    - biopython
    - pysam
    - matplotlib-base
    - numpy
    - pandas
    - htslib
    - smalt
    - r-base
    - r-getopt
    - r-mass
    - bwa
    - minimap2
    - snakemake
    - snakeviz
        
test:
  commands:
    - tradis --help

about:
  home: https://github.com/quadram-institute-bioscience/QuaTradis
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: 'A set of tools to analyse the output from TraDIS analyses'

extra:
  skip-lints:
    - uses_setuptools  # uses pkg_resources
  recipe-maintainers:
    - sbastkowski
    - maplesond
    - thanhleviet
  doi:
    - 10.1093/bioinformatics/btw022
