{% set name = "sage-proteomics" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower  }}
  version: {{ version  }}

build:
  number: 0

source:
  url: https://github.com/lazear/sage/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 99e97938574c14b295e3b706fea9cd4e2cca784cb0718fd576a18769c332cd05

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.62.0
  host:
  run:

test:
  commands:
    - sage --help

about:
  home: https://github.com/lazear/sage
  license: MIT
  license_file: LICENSE
  doc_url: https://lazear.github.io/sage/
  dev_url: https://github.com/lazear/sage
  summary: "Proteomics searching so fast it feels like magic."

extra:
  recipe-maintainers:
    - ypriverol
    - lazear
