{% set name = "sage-proteomics" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower  }}
  version: {{ version  }}

build:
  number: 0

source:
  url: https://github.com/lazear/sage/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a1eb26ca20ce2aa2b1799a4c7d3912c23643fe6656cb6ce56d72ddc944e4f4d9

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.62.0
  host:
  run:

test:
  commands:
    - sage --help

about:
  home: https://github.com/lazear/sage
  license: MIT
  license_file: LICENSE
  doc_url: https://lazear.github.io/sage/
  dev_url: https://github.com/lazear/sage
  summary: "Proteomics searching so fast it feels like magic."

extra:
  recipe-maintainers:
    - ypriverol
    - lazear
