{% set name = "sage-proteomics" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower  }}
  version: {{ version  }}

build:
  number: 0

source:
  url: https://github.com/lazear/sage/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 39f35406a09c9ea1c44086b9a154068eb2b543c8d139b1e28a0d64c48886b8af

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.62.0
  host:
  run:

test:
  commands:
    - sage --help

about:
  home: https://github.com/lazear/sage
  license: MIT
  license_file: LICENSE
  doc_url: https://lazear.github.io/sage/
  dev_url: https://github.com/lazear/sage
  summary: "Proteomics searching so fast it feels like magic."

extra:
  recipe-maintainers:
    - ypriverol
    - lazear
