{% set name = "sage-proteomics" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower  }}
  version: {{ version  }}

build:
  number: 0

source:
  url: https://github.com/lazear/sage/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8913f021e36c219ac7fbbabaa01d05ba1d79f3f0441a4e452dd3a9807bd25a6b

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.62.0
  host:
  run:

test:
  commands:
    - sage --help

about:
  home: https://github.com/lazear/sage
  license: MIT
  license_file: LICENSE
  doc_url: https://lazear.github.io/sage/
  dev_url: https://github.com/lazear/sage
  summary: "Proteomics searching so fast it feels like magic."

extra:
  recipe-maintainers:
    - ypriverol
    - lazear
